
name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
          DOCSEARCH_APP_KEY: ${{ secrets.DOCSEARCH_APP_KEY }}
          DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }}
          RESUME_PW: ${{ secrets.RESUME_PW }}
          PORTFOLIO_PW: ${{ secrets.PORTFOLIO_PW }}
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

          DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }} >> .env
          DOCSEARCH_APP_KEY: ${{ secrets.DOCSEARCH_APP_KEY }} >> .env
          DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }} >> .env
          RESUME_PW: ${{ secrets.RESUME_PW }} >> .env
          PORTFOLIO_PW: ${{ secrets.PORTFOLIO_PW }} >> .env

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Deploy Docs
          branch: gh-pages
          folder: src/.vuepress/dist
